### ISSUE TITLE
license

### ISSUE THREAD

**Issue by oleksandr-shvets** [tapmod/demo-tshirt#2]
Please add license.txt. Can I use listed code in commercial projects?

**Comment by OlegShuldiakov** [comment]
demo-tshirt - and what is your participation in this project?

**Comment by OlegShuldiakov** [comment]
also our development department received this information from you:  
**Мне кажется, что для конфигуратора 3д моделей товаров, интегрируемый в магазины заказчиков, React — не лучшее решение. Я бы смотрел в сторону WebComponents, которые уже имеют полную поддержку во всех основных браузерах, без дополнительных скриптов (за исключением Edge, для которого еще нужны полифилы).
Для реализации one-way-dataflow можно применить так называемый "исчезающий" фреймворк Svelte.

Для начала оптимизации, рекомендую перейти на Preact, который полностью совместим по api с React, но гораздо легче (в 35 раз) и быстрее.

На следующем шаге можно внедрить библиотечку Proppy. Вместе с гидрированием (пре-рендерингом) jsx в html, такое решение позволит абстрагировать клиентский код от react, и интегрировать 3д конфигуратор в любой фреймворк, используемый на сайте заказчика.

https://www.webcomponents.org W3C Standard
https://skatejs.netlify.com/ React-like One Way Dataflow WebComponents
https://preactjs.com 3kb
https://proppyjs.com Use react props in React/Preact, Vue, RxJS (Angular)
https://github.com/master-atul/react-webcomponentify Export react components to WebComponents
https://preactjs.com/guide/v10/server-side-rendering Pre-rendering jsx to html
https://github.com/choojs/nanocomponent-adapters
https://svelte.dev**

To confirm your qualifications, attach 2 working projects that you completed completely using these tools. our development department will check the data that you have provided and on the basis of this, a decision will be made on the advisability of communicating with you.

Thank you for contacting us. with respect.

**Comment by OlegShuldiakov** [comment]
![WebComponents, (P)React, react-props   Hydration · Issue #1 · tapmod_demo-tshirt - Google Chrome 2019-12-29 01 09 06](https://user-images.githubusercontent.com/59194755/71547895-85a3ca00-29d8-11ea-8ebe-338b479b5e62.jpg)

**Comment by oleksandr-shvets** [comment]
Нет так нет. Сказали бы сразу что вы сомневаетесь... в текстовом виде, чтобы исключить недопонимание и двусмысленность... как особенности нейронных сетей по запоминанию и хранению информации (Attention Mechanisms and Context Vector in deep neural networks).

**Comment by oleksandr-shvets** [comment]
Не звоните мне больше без предупреждения! Пишите лучше текстом.

**Comment by OlegShuldiakov** [comment]
@alexander-shvets добрый день, в тексте выше мы не нашли отказ с нашей стороны от предоставления вам какой либо информации или право на использование каких либо Ваших наработок или разработок которые Вы исполняли для нас на что вы можете иметь какие то ни было права на дальнейшее коммерческое или некоммерческое использования в своих интересах. мы просим указать нам на такие места в нашем проекте для дальнейшего анализа и проверки в соответствие с вашей  квалификацией. если же вы затрудняетесь предоставить нам данную информацию, нам бы хотелось получить письменный отказ от данного запроса в ленте этой переписки. спасибо всего вам хорошего. 

PS/: Мы не будем звонить Вам без предупреждения больше некогда! ;) писать текстом вам в личные каналы связи до прояснения ситуации с вашей квалификацией и решения данного вопроса.

**Comment by oleksandr-shvets** [comment]
@OlegShuldiakov Здравствуйте! Что значит "исполнял для вас"??? Я вам обязан чем-то? Вы просили меня вам помочь, я помог. Теперь вы просите меня опять... провести анализ вашего проекта. Если вы сомневаетесь в моей квалификации то тогда зачем просите?

**Comment by OlegShuldiakov** [comment]
alexander-shvets от вас нам поступил вопрос с таким запросом - **Please add license.txt. Can I use listed code in commercial projects?** я повторяю вопрос и запрос - что вы бы хотели использовать в личных целях по тем задачам которые вы исполняли для нас? и что конкретно вы исполняли для нас? если вы нечего не делали в чем была суть запроса от вас? если вы что то делали предоставьте конкретные строчки кода или те задачи которые вы делали для нас которые в дальнейшем хотели бы использовать в коммерческих целях
, в личных целях.  если вам еще что то непонятно не стесняйтесь спросить меня еще раз.

**Comment by oleksandr-shvets** [comment]
@OlegShuldiakov повторю то что я писал вам в телеграм и фейсбук: 
я сделал для вас как минимум половину демки (функционал, без UI стилей). Я бы и UI допилил, но уснул. И вы решили доделать все сами, когда я спал.
В последствии, вы успешно презентовали эту демку своему заказчику — Ikea. А мне отключили доступ к репозиторию, и забанили в мессенжере.

**Comment by OlegShuldiakov** [comment]
вы кажется неправильно меня поняли alexander-shvets - "демки" - эта формулировка мне не понятна, соответственно мне не понятно фраза **я сделал для вас** ... **(функционал, без UI стилей)** суть моего запроса заключается в том что КОНКРЕТНО вы сделали и на что КОНКРЕТНО вы запрашиваете коммерческое использование или использование в личных целях? 

Так-же хочу заметить что ваши сны не имеют нечего общего к решению вопроса описанного выше, также от вас поступила просьба не совершать вам личностные звонки и перестать контактировать в личных сообщениях и менеджерах во всех видах.

**Comment by oleksandr-shvets** [comment]
### да не надо мне от вас никакого кода и лицензий

Просто заплатите мне хотя-бы часть от того, что обещали.

И перестать контактировать со мной в личных сообщениях и менеджерах во всех видах я вас не просил. Это решение @OlegShuldiakov приняли вы, лично. Я просил только про звонки.

**Comment by oleksandr-shvets** [comment]
## товарищ Шулдяков! 

Опасайтесь! К вам уже выехала группа ОБХСС!     
(Они вычислили ваш адрес по протоколу Ай-Пи)

<img src="http://cont.ws/uploads/pic/2017/7/71fad829d4a242a7dea3997d3041768f.jpg"/>

**Comment by OlegShuldiakov** [comment]
? я повторяю вопрос и запрос - что вы бы хотели использовать в личных целях по тем задачам которые вы исполняли для нас? так что вы сделали то в итоге? мне не понятно

**Comment by OlegShuldiakov** [comment]
у меня сложилось впечатление что вы не можете точно сформулировать что вы сделали, как при таком варианте это возможно оценить?

**Comment by oleksandr-shvets** [comment]
@OlegShuldiakov 
Я сделал почти весь функционал проекта Ikea-demo, Виталий доделал UI.
Вот лог:
<img src="https://images2.imgbox.com/8d/78/vttNIsCh_o.png"/>

**Comment by OlegShuldiakov** [comment]
ну наконец то, мы проверим эти данные и я вернусь к вам.

**Comment by OlegShuldiakov** [comment]
![photo_2020-01-14_13-50-55](https://user-images.githubusercontent.com/59194755/72321141-b91f6d80-36d5-11ea-871e-2603188233ee.jpg)  -  по объему работы можно сказать, что он привнес 325/(807+325) = 28%

https://tapmod.studio/ikea-shvets/  - это проект на момент его сдачи ним ( какаето неработающая хрень мне кажется )

Это комментарий непосредственного менеджера проекта - Мой фидбек по работе с Александром: я на этом проекте был в роли менеджера, коммуникации с Александром практически не было. Ни одного вопроса от него по проекту не задано, ни одна договоренность по чекпойнтам не была выполнена. Фактически с моей стороны не было видно никаких признаков что что-либо делается по проекту.  моя оценка - эффективность ноль.

вопрос: на какую сумму вы претендуете?

**Comment by oleksandr-shvets** [comment]
@OlegShuldiakov 

(15+1 + 14+1)  / (15+1)  = 50%
А по количеству коммитов другая картина :)  Score базируется на количестве байт (объеме) кода, а Commits на количестве логически-атомарных частей архитектуры системы. Но, к сожалению, ни первая ни вторая метрика не несет прямой информации  о количестве времени, потраченного на работу. Все субъективно, то есть зависит от того, или иного программиста.

В понедельник мы договорились, что на следующий день после старта, я покажу что-то работающее. Я так и сделал. Далее, была договоренность, что в пятницу будет чекпоинт, где будет реализован основной функционал, а окончательная сдача проекта в понедельник. Но,  менеджер проекта позвонил мне в четверг вечером и сказал, что сроки сокращаются до пятницы 17:00. На момент пятницы 9:00, основной функционал был залит в репозиторий. Я планировал доделать работу до 17:00, но, проспал до 13:00... Виталий, не сумевший связаться со мной, доделал все сам. Если моя недоделанная работа являлась "непонятной и неработающей", то возникает вопрос почему Виталий использовал ее за основу, а на сделал весь проект с нуля?  
Поэтому, претендую на 36% = $300 * 36% = $108

P.S.
Для исключения подобных недоразумений, рекомендую вам использовать письменные договоренности в виде тасков в какой-то системе, типа Github Issues, или Jira.

**Comment by OlegShuldiakov** [comment]
108 - нет, 

по факту я вижу что вот это  https://tapmod.studio/ikea-shvets/ - 36% неработающего говнокода. 

также не выполнение условий оговоренных тестовым заданием - БЫТЬ на связи со своим менеджером проекта - не выполнялось. 

$50 - максимум

**Comment by oleksandr-shvets** [comment]
@OlegShuldiakov

В какое время я не был на связи со своим менеджером проекта (Евгением)? После 18го декабря он мне ничего не писал, и не звонил.   
Из чего состоят 64% кода вашего проекта? (если моя — 36%)      
Большую часть этого кода составляет копипаст HTML/CSS с сайта ikea.com и никак не обговоренный ранее функционал (Details Configuration):    
<img src="http://imageshack.com/a/img923/9374/5TZRZL.png" height="100"/>

**Comment by oleksandr-shvets** [comment]
<img src="http://kotomatrix.ru/images/lolz/2012/01/02/kA.jpg" width="64%"/> 
@OlegShuldiakov     

> по факту я вижу что вот это https://tapmod.studio/ikea-shvets/ - 36% неработающего говнокода.

Еще раз ПОВТОРЯЮ: приводите **аргументы**, прежде чем утверждать что-либо подобное. По каким признакам вы определяете "говно" в скомпилированном(!) коде?      
А в первую очередь, смотрите на своё, прежде чем как-то называть чужое:               

**Безсостоятельные** (stateless) компоненты объемом 425+ строк, с 8-ю уровнями вложенности (например `MainView.js`), это нормально?      

 А как реализован подъем состояния? от низших компонентов к компонентам высшего (порядка).  Это делают ваши любимые хуки... Что-то не видно среди них [`useContext`](https://ru.reactjs.org/docs/hooks-reference.html#usecontext) или `useReducer`.     

Чем я занимался первые два для? Изучением новой для меня концепции хуков. Которую, судя по отсутствию в вашем коде `useContext` вы сами до сих пор не усвоили до конца. 
Чем же являются реакт-хуки? В принципе, можно сказать, что это развитие концепции "ленивой" инициализации, описанной (7 лет назад) мною в статье [Нужны ли языку JavaScript классы?](https://habr.com/ru/post/175029/#init)       

Будем и дальше спорить о том, чей код больше "воняет"?     

Итак, жду от вас всего лишь __$108__, или _**аргументированных**_ разъяснений вашей точки зрения.

**Comment by OlegShuldiakov** [comment]
по факту анализа текущей ситуации мы готовы обсудить это в голосовом режиме по ссылке meet.google.com/dfc-seot-piu назначьте время когда вам будет удобно.
